# Generated by Django 3.1.4 on 2021-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(max_length=4)),
                ('route', models.CharField(max_length=4)),
                ('direction', models.CharField(max_length=1)),
                ('stops', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField()),
                ('name_tc', models.CharField(max_length=50)),
                ('name_sc', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
