# Generated by Django 3.1.4 on 2021-01-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='stops',
            new_name='stops_i',
        ),
        migrations.RemoveField(
            model_name='route',
            name='direction',
        ),
        migrations.AddField(
            model_name='route',
            name='dest_en',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='dest_sc',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='dest_tc',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='orig_en',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='orig_sc',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='orig_tc',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='stops_o',
            field=models.CharField(default='temp', max_length=1000),
            preserve_default=False,
        ),
    ]
